name: 'untitled'
version: 0.0.1
description: An absolute bare-bones web app.
#author: Your Name <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

#dependencies:
#  my_dependency: any

dependencies:
args: '>=0.10.0 <0.14.0'
shelf:
shelf_route:
sqljocky: 0.14.1
logging: 0.11.3+1

dev_dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^1.0.1'
