name: 'team6exercise'
version: 0.0.1
description: An absolute bare-bones web app.
#author: Your Name <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'


#dependencies:
#  my_dependency: any
dependencies:
     path:
     browser:
     shelf:
     shelf_route:
     sqljocky:
     json_object: any
     json:
     route_hierarchical:
     jsonx:
